module.exports = {
  development:{
    DBHOST:'localhost',
    DBUSER:'root',
    DBPASS:'',
    DEBUG:true,
    LOGPREFIX:'/mnt/LOE/',
    LOGPREFIX_REP:'/var/www/html/'
  },
  testing:{
    DBHOST:'localhost',
    DBUSER:'root',
    DBPASS:'',
    DEBUG:true,
    LOGPREFIX:'/mnt/LOE/',
    LOGPREFIX_REP:'/var/www/html/'
  },
  production:{
    DBHOST:'localhost',
    DBUSER:'root',
    DBPASS:'',
    DEBUG:true,
    LOGPREFIX:'/mnt/LOE/',
    LOGPREFIX_REP:'/var/www/html/'
  }
};
